# ============================
# DASHBOARD CONFIGURATION
# ============================

# ----------------------------
# Startpage
# ----------------------------
- name: Startpage
  width: slim
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          title: Google
          engine: google
          suggestions: true
          autofocus: true

        - type: monitor
          title: Services
          cache: 30s
          sites:
            - title: N8N
              url: https://n8n.dharmintech.org
              icon: si:n8n
            - title: Proxmox
              url: https://192.168.0.190:8006
              icon: si:proxmox
            - title: Pi-hole
              url: http://192.168.0.227/admin/login
              icon: si:pihole
            - title: Vaultwarden
              url: https://vw.dharmintech.org/
              icon: si:vaultwarden
            - title: Nginx Proxy Manager
              url: http://192.168.0.195:81/login
              icon: si:nginx

        - type: bookmarks
          groups:
            - title: General
              links:
                - title: Gmail
                  url: https://mail.google.com/mail/u/0/
                  icon: si:gmail
                - title: GitLab
                  url: https://gitlab.com/
                  icon: si:gitlab
                - title: GitHub
                  url: https://github.com/
                  icon: si:github
            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                  icon: si:youtube
                - title: Prime Video
                  url: https://www.primevideo.com/
                  icon: si:primevideo
                - title: Disney+
                  url: https://www.disneyplus.com/
                  icon: si:disneyplus
            - title: Dev & Network Tools
              links:
                - title: IT-Tools
                  url: https://it-tools.tech/
                  icon: si:tools
                - title: CyberChef
                  url: https://gchq.github.io/CyberChef/
                  icon: si:cyberchef
                - title: QuickRef
                  url: https://www.quickref.me/
                  icon: si:book
                - title: OverApi
                  url: https://overapi.com/
                  icon: si:api
                - title: ipinfo.io
                  url: https://ipinfo.io/
                  icon: si:ipfs

# ----------------------------
# Markets
# ----------------------------
- name: Markets
  columns:
    - size: small
      widgets:
        - type: markets
          title: Indices
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: DX-Y.NYB
              name: Dollar Index

        - type: markets
          title: Crypto
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum

        - type: markets
          title: Stocks
          sort-by: absolute-change
          markets:
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
            - symbol: GOOGL
              name: Google
            - symbol: AMD
              name: AMD
            - symbol: RDDT
              name: Reddit
            - symbol: AMZN
              name: Amazon
            - symbol: TSLA
              name: Tesla
            - symbol: INTC
              name: Intel
            - symbol: META
              name: Meta

    - size: full
      widgets:
        - type: rss
          title: News
          style: horizontal-cards
          cache: 15m
          feeds:
            - url: https://feeds.bloomberg.com/markets/news.rss
              title: Bloomberg
            - url: https://moxie.foxbusiness.com/google-publisher/markets.xml
              title: Fox Business
            - url: https://moxie.foxbusiness.com/google-publisher/technology.xml
              title: Fox Business

        - type: group
          widgets:
            - type: reddit
              show-thumbnails: true
              subreddit: technology
            - type: reddit
              show-thumbnails: true
              subreddit: wallstreetbets

        - type: videos
          style: grid-cards
          collapse-after-rows: 3
          channels:
            - UCvSXMi2LebwJEM1s4bz5IBA # New Money
            - UCV6KDgJskWaEckne5aPA0aQ # Graham Stephan
            - UCAzhpt9DmG6PnHXjmJTvRGQ # Federal Reserve

    - size: small
      widgets:
        - type: rss
          title: News
          limit: 30
          collapse-after: 13
          cache: 30m
          feeds:
            - url: https://www.ft.com/technology?format=rss
              title: Financial Times
            - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
              title: Wall Street Journal

# ----------------------------
# Home
# ----------------------------
- name: Home
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
              title: ciechanow.ski
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
              title: samwho.dev
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed

        - type: twitch-channels
          channels:
            - theprimeagen
            - j_blow
            - piratesoftware
            - cohhcarnage
            - christitustech
            - EJ_SA

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
            - UCsBjURrPoezykLs9EqgamOA # Fireship
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: weather
          location: Maineville, Ohio, United States
          units: imperial
          hour-format: 12h

        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: PLTR
              name: Palantir Technologies

        - type: releases
          cache: 1d
          repositories:
            - glanceapp/glance
            - vaultwarden/vaultwarden
            - pihole/admin

# ----------------------------
# Instater (To-Do + Server Stats)
# ----------------------------
- name: Instater
  columns:
    - size: full
      widgets:
        # ✅ To-Do List
        - type: to-do
          id: personal-todo
          title: My Tasks

        # 🖥️ Server Stats
        - type: server-stats
          servers:
            - type: local
              name: Glance Host
              hide-mountpoints-by-default: false
# ----------------------------
# OSINT
# ----------------------------
- name: OSINT
  columns:
    - size: full
      widgets:
        - type: bookmarks
          groups:
            - title: OSINT Tools
              links:
                - title: CVE Details
                  url: https://www.cvedetails.com/
                  icon: si:cve
                - title: Whois Lookup
                  url: http://whois.domaintools.com/
                  icon: si:whois
                - title: VirusTotal
                  url: https://www.virustotal.com/gui/home
                  icon: si:virustotal
                - title: IP Logger
                  url: https://iplogger.org/
                  icon: si:ip
                - title: OSINT Framework
                  url: https://osintframework.com/
                  icon: si:search
                - title: Shodan
                  url: https://www.shodan.io/
                  icon: si:shodan
                - title: Recon-ng
                  url: https://github.com/lanmaster53/recon-ng
                  icon: si:github

    - size: small
      widgets:
        - type: rss
          title: OSINT News
          cache: 30m
          feeds:
            - url: https://www.schneier.com/blog/atom.xml
              title: Schneier on Security
            - url: https://www.darkreading.com/rss.xml
              title: Dark Reading

        - type: group
          widgets:
            - type: reddit
              subreddit: osint
              show-thumbnails: true
            - type: reddit
              subreddit: netsec
              show-thumbnails: true

    - size: small
      widgets:
        - type: search
          title: Search OSINT Tools
          engine: google
          suggestions: true
          autofocus: true
          placeholder: "Search for OSINT tools or vulnerabilities..."

